In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('DATA/bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [9]:
features = data[:,0:4]

In [10]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

In [13]:
from sklearn.model_selection import train_test_split


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [15]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [16]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [17]:
len(X_train)

919

In [18]:
len(X_test)

453

In [19]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [20]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [21]:
len(y_train)

919

In [22]:
len(y_test)

453

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
scaler_object = MinMaxScaler()

In [39]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [40]:
scaled_X_train = scaler_object.transform(X_train)

In [41]:
scaled_X_test = scaler_object.transform(X_test)

In [68]:
scaled_X_train.max()

1.0000000000000002

In [43]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [44]:
scaled_X_train.min()

0.0

In [45]:
from keras.models import Sequential
from keras.layers import Dense

In [46]:
model = Sequential()

model.add(Dense(4, input_dim = 4, activation = 'relu'))
model.add(Dense(8, activation= 'relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [47]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [53]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
 - 0s - loss: 0.0163 - acc: 0.9967
Epoch 2/50
 - 0s - loss: 0.0159 - acc: 0.9967
Epoch 3/50
 - 0s - loss: 0.0159 - acc: 0.9967
Epoch 4/50
 - 0s - loss: 0.0162 - acc: 0.9967
Epoch 5/50
 - 0s - loss: 0.0156 - acc: 0.9967
Epoch 6/50
 - 0s - loss: 0.0157 - acc: 0.9967
Epoch 7/50
 - 0s - loss: 0.0156 - acc: 0.9967
Epoch 8/50
 - 0s - loss: 0.0157 - acc: 0.9967
Epoch 9/50
 - 0s - loss: 0.0155 - acc: 0.9967
Epoch 10/50
 - 0s - loss: 0.0153 - acc: 0.9967
Epoch 11/50
 - 0s - loss: 0.0152 - acc: 0.9967
Epoch 12/50
 - 0s - loss: 0.0150 - acc: 0.9967
Epoch 13/50
 - 0s - loss: 0.0152 - acc: 0.9967
Epoch 14/50
 - 0s - loss: 0.0150 - acc: 0.9967
Epoch 15/50
 - 0s - loss: 0.0152 - acc: 0.9967
Epoch 16/50
 - 0s - loss: 0.0148 - acc: 0.9967
Epoch 17/50
 - 0s - loss: 0.0150 - acc: 0.9967
Epoch 18/50
 - 0s - loss: 0.0149 - acc: 0.9967
Epoch 19/50
 - 0s - loss: 0.0149 - acc: 0.9967
Epoch 20/50
 - 0s - loss: 0.0148 - acc: 0.9967
Epoch 21/50
 - 0s - loss: 0.0146 - acc: 0.9967
Epoch 22/50
 - 0s - lo

In [56]:
model.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [62]:
model.evaluate(X_test, y_test)

453/453 [==============================] - 0s 12us/step


[0.39235863266763127, 0.9713024282560706]

In [57]:
model.metrics_names

['loss', 'acc']

In [59]:
from sklearn.metrics import confusion_matrix, classification_report

In [64]:
predictions = model.predict_classes(scaled_X_test)

In [65]:
confusion_matrix(y_test, predictions)

array([[254,   3],
       [  0, 196]], dtype=int64)

In [66]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       1.00      0.99      0.99       257
        1.0       0.98      1.00      0.99       196

avg / total       0.99      0.99      0.99       453



In [69]:
model.save('Currencies.h5')

In [70]:
from keras.models import load_model

In [71]:
new_model = load_model('Currencies.h5')